# Generated by Django 2.2.1 on 2019-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='descrip',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
